/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cadesperlich' at '2/21/16 9:18 PM' with Gradle 2.6
 *
 * @author cadesperlich, @date 2/21/16 9:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
